[bin] meating: cleanup docs and comments

diff --git a/bin/meating b/bin/meating
--- a/bin/meating
+++ b/bin/meating
@@ -1,19 +1,19 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
-# List calendar today's events.
+# List today's upcoming calendar events with meeting link.
 #
-# To get calendar UID's run `icalbuddy calendars`
-
-# Current calendars
-# Fermyon: 30B85FD0-6646-40FD-B5EC-14B1C19CF523
-# iCloud:  1A89C98B-4408-4A76-8B82-AF0BD0B8664F
+#   To get calendar UID's run `icalbuddy calendars`
+#
+#   Current calendar UID's:
+#     Fermyon: 30B85FD0-6646-40FD-B5EC-14B1C19CF523
+#     iCloud:  1A89C98B-4408-4A76-8B82-AF0BD0B8664F
 
 calendars='30B85FD0-6646-40FD-B5EC-14B1C19CF523,1A89C98B-4408-4A76-8B82-AF0BD0B8664F'
 
 if ! hash icalbuddy &>/dev/null; then
-    >&2 echo 'error: icalbuddy not found'
-    >&2 echo 'brew install icalbuddy'
+    >&2 echo 'error: icalbuddy not found.  Install using brew...'
+    >&2 echo '  brew install icalbuddy'
     exit 1
 fi
 
