[zsh] apply latest pure updates

diff --git a/zsh/functions/prompt_pure_setup b/zsh/functions/prompt_pure_setup
--- a/zsh/functions/prompt_pure_setup
+++ b/zsh/functions/prompt_pure_setup
@@ -197,7 +197,7 @@ prompt_pure_async_vcs_info() {
   zstyle ':vcs_info:*' max-exports 2
   # export branch (%b) and git toplevel (%R)
   zstyle ':vcs_info:git*' formats '%b' '%R'
-  zstyle ':vcs_info:git*' actionformats '%b|%a' '%R'
+  zstyle ':vcs_info:git*' actionformats '%F{red}%a%f%  → %F{blue}%b%f' '%R'
 
   vcs_info
 
@@ -227,9 +227,37 @@ prompt_pure_async_git_fetch() {
   # set GIT_TERMINAL_PROMPT=0 to disable auth prompting for git fetch (git 2.3+)
   export GIT_TERMINAL_PROMPT=0
   # set ssh BachMode to disable all interactive ssh password prompting
-  export GIT_SSH_COMMAND=${GIT_SSH_COMMAND:-"ssh -o BatchMode=yes"}
+  export GIT_SSH_COMMAND="${GIT_SSH_COMMAND:-"ssh"} -o BatchMode=yes"
 
-  command git -c gc.auto=0 fetch &>/dev/null || return 99
+	# Default return code, indicates Git fetch failure.
+	local fail_code=99
+
+	# Guard against all forms of password prompts. By setting the shell into
+	# MONITOR mode we can notice when a child process prompts for user input
+	# because it will be suspended. Since we are inside an async worker, we
+	# have no way of transmitting the password and the only option is to
+	# kill it. If we don't do it this way, the process will corrupt with the
+	# async worker.
+	setopt localtraps monitor
+
+	# Make sure local HUP trap is unset to allow for signal propagation when
+	# the async worker is flushed.
+	trap - HUP
+
+	trap '
+		# Unset trap to prevent infinite loop
+		trap - CHLD
+		if [[ $jobstates = suspended* ]]; then
+			# Set fail code to password prompt and kill the fetch.
+			fail_code=98
+			kill %%
+		fi
+	' CHLD
+
+	command git -c gc.auto=0 fetch >/dev/null &
+	wait $! || return $fail_code
+
+	unsetopt monitor
 
   # check arrow status after a successful git fetch
   prompt_pure_async_git_arrows $1
@@ -374,22 +402,27 @@ prompt_pure_async_callback() {
     prompt_pure_async_git_fetch|prompt_pure_async_git_arrows)
       # prompt_pure_async_git_fetch executes prompt_pure_async_git_arrows
       # after a successful fetch.
-      if (( code == 0 )); then
-        local REPLY
-        prompt_pure_check_git_arrows ${(ps:\t:)output}
-        if [[ $prompt_pure_git_arrows != $REPLY ]]; then
-          typeset -g prompt_pure_git_arrows=$REPLY
-          do_render=1
-        fi
-      elif (( code != 99 )); then
-        # Unless the exit code is 99, prompt_pure_async_git_arrows
-        # failed with a non-zero exit status, meaning there is no
-        # upstream configured.
-        if [[ -n $prompt_pure_git_arrows ]]; then
-          unset prompt_pure_git_arrows
-          do_render=1
-        fi
-      fi
+      case $code in
+        0)
+          local REPLY
+          prompt_pure_check_git_arrows ${(ps:\t:)output}
+          if [[ $prompt_pure_git_arrows != $REPLY ]]; then
+            typeset -g prompt_pure_git_arrows=$REPLY
+            do_render=1
+          fi
+          ;;
+        99|98)
+          # Git fetch failed.
+          ;;
+        *)
+          # Non-zero exit status from prompt_pure_async_git_arrows,
+          # indicating that there is no upstream configured.
+          if [[ -n $prompt_pure_git_arrows ]]; then
+            unset prompt_pure_git_arrows
+            do_render=1
+          fi
+          ;;
+      esac
       ;;
   esac
 
@@ -402,12 +435,57 @@ prompt_pure_async_callback() {
   unset prompt_pure_async_render_requested
 }
 
+prompt_pure_state_setup() {
+	setopt localoptions noshwordsplit
+
+	# Check SSH_CONNECTION and the current state.
+	local ssh_connection=${SSH_CONNECTION:-$PROMPT_PURE_SSH_CONNECTION}
+	local username
+	if [[ -z $ssh_connection ]] && (( $+commands[who] )); then
+		# When changing user on a remote system, the $SSH_CONNECTION
+		# environment variable can be lost, attempt detection via who.
+		local who_out
+		who_out=$(who -m 2>/dev/null)
+		if (( $? )); then
+			# Who am I not supported, fallback to plain who.
+			who_out=$(who 2>/dev/null | grep ${TTY#/dev/})
+		fi
+
+		local reIPv6='([a-f0-9:]+:+)+[a-f0-9]+'  # Simplified, but matches loopback as well (::1).
+		local reIPv4='([0-9]{1,3}\.){3}[0-9]+'   # Simplified, allows invalid ranges.
+		# Here we assume two non-consecutive periods represents a
+		# hostname. This matches foo.bar.baz, but not foo.bar.
+		local reHostname='([.][^. ]+){2}'
+
+		# Usually the remote address is surrounded by parenthesis, but
+		# not on all systems (e.g. busybox).
+		local -H MATCH MBEGIN MEND
+		if [[ $who_out =~ "\(?($reIPv4|$reIPv6|$reHostname)\)?\$" ]]; then
+			ssh_connection=$MATCH
+
+			# Export variable to allow detection propagation inside
+			# shells spawned by this one (e.g. tmux does not always
+			# inherit the same tty, which breaks detection).
+			export PROMPT_PURE_SSH_CONNECTION=$ssh_connection
+		fi
+		unset MATCH MBEGIN MEND
+	fi
+
+	# show username@host if logged in through SSH
+	[[ -n $ssh_connection ]] && username='%F{242}%n@%m%f'
+
+	# show username@host if root, with username in white
+	[[ $UID -eq 0 ]] && username='%F{white}%n%f%F{242}@%m%f'
+
+	typeset -gA prompt_pure_state
+	prompt_pure_state=(
+		username "$username"
+	)
+}
+
 prompt_pure_setup() {
   # Prevent percentage showing up if output doesn't end with a newline.
   export PROMPT_EOL_MARK=''
-
-  # disallow python virtualenvs from updating the prompt
-  export VIRTUAL_ENV_DISABLE_PROMPT=1
 
   prompt_opts=(subst percent)
 
@@ -432,16 +510,43 @@ prompt_pure_setup() {
   add-zsh-hook preexec prompt_pure_preexec
 
   # show username@host if logged in through SSH
-  [[ "$SSH_CONNECTION" != '' ]] && prompt_pure_username='%F{242}[%n@%m]%f'
+  # [[ "$SSH_CONNECTION" != '' ]] && prompt_pure_username='%F{242}[%n@%m]%f'
 
   # show username@host if root, with username in white
-  [[ $UID -eq 0 ]] && prompt_pure_username='%F{white}[%n%f%F{242}@%m]%f'
+  # [[ $UID -eq 0 ]] && prompt_pure_username='%F{white}[%n%f%F{242}@%m]%f'
 
   # if a virtualenv is activated, display it in grey
   PROMPT='%(12V.%F{242}%12v%f .)'
 
   # prompt turns red if the previous command didn't exit with 0
-  PROMPT+='%(?.%F{003}.%F{red})❯%f '
+  PROMPT+='%(?.%F{003}.%F{red}$(exitname))${PURE_PROMPT_SYMBOL:-❯}%f '
+
+  # Store prompt expansion symbols for in-place expansion via (%). For
+  # some reason it does not work without storing them in a variable first.
+  typeset -ga prompt_pure_debug_depth
+  prompt_pure_debug_depth=('%e' '%N' '%x')
+
+  # Compare is used to check if %N equals %x. When they differ, the main
+  # prompt is used to allow displaying both file name and function. When
+  # they match, we use the secondary prompt to avoid displaying duplicate
+  # information.
+  local -A ps4_parts
+  ps4_parts=(
+    depth     '%F{yellow}${(l:${(%)prompt_pure_debug_depth[1]}::+:)}%f'
+    compare   '${${(%)prompt_pure_debug_depth[2]}:#${(%)prompt_pure_debug_depth[3]}}'
+    main      '%F{blue}${${(%)prompt_pure_debug_depth[3]}:t}%f%F{242}:%I%f %F{242}@%f%F{blue}%N%f%F{242}:%i%f'
+    secondary '%F{blue}%N%f%F{242}:%i'
+    prompt    '%F{242}>%f '
+  )
+  # Combine the parts with conditional logic. First the `:+` operator is
+  # used to replace `compare` either with `main` or an ampty string. Then
+  # the `:-` operator is used so that if `compare` becomes an empty
+  # string, it is replaced with `secondary`.
+  local ps4_symbols='${${'${ps4_parts[compare]}':+"'${ps4_parts[main]}'"}:-"'${ps4_parts[secondary]}'"}'
+
+  # Improve the debug prompt (PS4), show depth by repeating the +-sign and
+  # add colors to highlight essential parts like file and function name.
+  PROMPT4="${ps4_parts[depth]} ${ps4_symbols}${ps4_parts[prompt]}"
 }
 
 prompt_pure_setup "$@"
