[zsh] try out zplugin for size

diff --git a/zsh/functions/prompt_pure_setup b/zsh/functions/prompt_pure_setup
--- a/zsh/functions/prompt_pure_setup
+++ b/zsh/functions/prompt_pure_setup
@@ -229,35 +229,35 @@ prompt_pure_async_git_fetch() {
   # set ssh BachMode to disable all interactive ssh password prompting
   export GIT_SSH_COMMAND="${GIT_SSH_COMMAND:-"ssh"} -o BatchMode=yes"
 
-	# Default return code, indicates Git fetch failure.
-	local fail_code=99
+  # Default return code, indicates Git fetch failure.
+  local fail_code=99
 
-	# Guard against all forms of password prompts. By setting the shell into
-	# MONITOR mode we can notice when a child process prompts for user input
-	# because it will be suspended. Since we are inside an async worker, we
-	# have no way of transmitting the password and the only option is to
-	# kill it. If we don't do it this way, the process will corrupt with the
-	# async worker.
-	setopt localtraps monitor
+  # Guard against all forms of password prompts. By setting the shell into
+  # MONITOR mode we can notice when a child process prompts for user input
+  # because it will be suspended. Since we are inside an async worker, we
+  # have no way of transmitting the password and the only option is to
+  # kill it. If we don't do it this way, the process will corrupt with the
+  # async worker.
+  setopt localtraps monitor
 
-	# Make sure local HUP trap is unset to allow for signal propagation when
-	# the async worker is flushed.
-	trap - HUP
+  # Make sure local HUP trap is unset to allow for signal propagation when
+  # the async worker is flushed.
+  trap - HUP
 
-	trap '
-		# Unset trap to prevent infinite loop
-		trap - CHLD
-		if [[ $jobstates = suspended* ]]; then
-			# Set fail code to password prompt and kill the fetch.
-			fail_code=98
-			kill %%
-		fi
-	' CHLD
+  trap '
+    # Unset trap to prevent infinite loop
+    trap - CHLD
+    if [[ $jobstates = suspended* ]]; then
+      # Set fail code to password prompt and kill the fetch.
+      fail_code=98
+      kill %%
+    fi
+  ' CHLD
 
-	command git -c gc.auto=0 fetch >/dev/null &
-	wait $! || return $fail_code
+  command git -c gc.auto=0 fetch >/dev/null &
+  wait $! || return $fail_code
 
-	unsetopt monitor
+  unsetopt monitor
 
   # check arrow status after a successful git fetch
   prompt_pure_async_git_arrows $1
@@ -436,51 +436,51 @@ prompt_pure_async_callback() {
 }
 
 prompt_pure_state_setup() {
-	setopt localoptions noshwordsplit
+  setopt localoptions noshwordsplit
 
-	# Check SSH_CONNECTION and the current state.
-	local ssh_connection=${SSH_CONNECTION:-$PROMPT_PURE_SSH_CONNECTION}
-	local username
-	if [[ -z $ssh_connection ]] && (( $+commands[who] )); then
-		# When changing user on a remote system, the $SSH_CONNECTION
-		# environment variable can be lost, attempt detection via who.
-		local who_out
-		who_out=$(who -m 2>/dev/null)
-		if (( $? )); then
-			# Who am I not supported, fallback to plain who.
-			who_out=$(who 2>/dev/null | grep ${TTY#/dev/})
-		fi
+  # Check SSH_CONNECTION and the current state.
+  local ssh_connection=${SSH_CONNECTION:-$PROMPT_PURE_SSH_CONNECTION}
+  local username
+  if [[ -z $ssh_connection ]] && (( $+commands[who] )); then
+    # When changing user on a remote system, the $SSH_CONNECTION
+    # environment variable can be lost, attempt detection via who.
+    local who_out
+    who_out=$(who -m 2>/dev/null)
+    if (( $? )); then
+      # Who am I not supported, fallback to plain who.
+      who_out=$(who 2>/dev/null | grep ${TTY#/dev/})
+    fi
 
-		local reIPv6='([a-f0-9:]+:+)+[a-f0-9]+'  # Simplified, but matches loopback as well (::1).
-		local reIPv4='([0-9]{1,3}\.){3}[0-9]+'   # Simplified, allows invalid ranges.
-		# Here we assume two non-consecutive periods represents a
-		# hostname. This matches foo.bar.baz, but not foo.bar.
-		local reHostname='([.][^. ]+){2}'
+    local reIPv6='([a-f0-9:]+:+)+[a-f0-9]+'  # Simplified, but matches loopback as well (::1).
+    local reIPv4='([0-9]{1,3}\.){3}[0-9]+'   # Simplified, allows invalid ranges.
+    # Here we assume two non-consecutive periods represents a
+    # hostname. This matches foo.bar.baz, but not foo.bar.
+    local reHostname='([.][^. ]+){2}'
 
-		# Usually the remote address is surrounded by parenthesis, but
-		# not on all systems (e.g. busybox).
-		local -H MATCH MBEGIN MEND
-		if [[ $who_out =~ "\(?($reIPv4|$reIPv6|$reHostname)\)?\$" ]]; then
-			ssh_connection=$MATCH
+    # Usually the remote address is surrounded by parenthesis, but
+    # not on all systems (e.g. busybox).
+    local -H MATCH MBEGIN MEND
+    if [[ $who_out =~ "\(?($reIPv4|$reIPv6|$reHostname)\)?\$" ]]; then
+      ssh_connection=$MATCH
 
-			# Export variable to allow detection propagation inside
-			# shells spawned by this one (e.g. tmux does not always
-			# inherit the same tty, which breaks detection).
-			export PROMPT_PURE_SSH_CONNECTION=$ssh_connection
-		fi
-		unset MATCH MBEGIN MEND
-	fi
+      # Export variable to allow detection propagation inside
+      # shells spawned by this one (e.g. tmux does not always
+      # inherit the same tty, which breaks detection).
+      export PROMPT_PURE_SSH_CONNECTION=$ssh_connection
+    fi
+    unset MATCH MBEGIN MEND
+  fi
 
-	# show username@host if logged in through SSH
-	[[ -n $ssh_connection ]] && username='%F{242}%n@%m%f'
+  # show username@host if logged in through SSH
+  [[ -n $ssh_connection ]] && username='%F{242}%n@%m%f'
 
-	# show username@host if root, with username in white
-	[[ $UID -eq 0 ]] && username='%F{white}%n%f%F{242}@%m%f'
+  # show username@host if root, with username in white
+  [[ $UID -eq 0 ]] && username='%F{white}%n%f%F{242}@%m%f'
 
-	typeset -gA prompt_pure_state
-	prompt_pure_state=(
-		username "$username"
-	)
+  typeset -gA prompt_pure_state
+  prompt_pure_state=(
+    username "$username"
+  )
 }
 
 prompt_pure_setup() {
